convert Lens_and_wavefronts.png -resize 114x114 icon114.png
convert Lens_and_wavefronts.png -resize 135x135 icon135.png
convert Lens_and_wavefronts.png -resize 512x512 icon512.png
convert Lens_and_wavefronts.png -resize 144x144 res/drawable-xxhdpi/icon.png
convert Lens_and_wavefronts.png -resize 96x96 res/drawable-xhdpi/icon.png
convert Lens_and_wavefronts.png -resize 72x72 res/drawable-hdpi/icon.png
convert Lens_and_wavefronts.png -resize 72x72 res/drawable-hdpi/icon.png
convert Lens_and_wavefronts.png -resize 48x48 res/drawable-mdpi/icon.png
convert Lens_and_wavefronts.png -resize 32x32 res/drawable-ldpi/icon.png
